name: Build and Publish Docker image
on:
    release:
        types: [published]

jobs:
    push-to-docker-up-and-ghcr:
        runs-on: ubuntu-latest
        permissions: 
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v3 # i need access to docker.yml in the branch
            - name: Login to dockerHub 
              uses: docker/login-action@v3 #to login
              with:
                    username: '${{ secrets.DOCKER_USERNAME }}'
                    password: '${{ secrets.DOCKER_PASSWORD }}'
            - name: Login to dockerHub 
              uses: docker/login-action@v3 #to login
              with:
                    registry: ghcr.io
                    username: '${{ github.actor}}'
                    password: '${{ secrets.GITHUB_TOKEN }}'
            - name: Extract metadata
              id: metadata
              uses: docker/metadata-action@v4
              with:
                images: |
                 mohammedrifaii00/repo-test
                 ghcr.io/${{github.repository}}
                tags: | #to filter tags and latest will be generated by default
                    type = semver,pattern={{version}}
                    type = semver,pattern= {{major}},{{minor}}
            - name: Build and publish image docker
              uses: docker/build-push-action@v4
              with:
                context: . #root folder
                file: ./Dockerfile # the path to our docker file
                push: true
                tags: ${{steps.metadata.outputs.tags}}
                labels: ${{steps.metadata.outputs.labels}}
            - name: log lavels and tags
              run: | 
                echo ${{steps.metadata.outputs.tags}}
                echo ${{steps.metadata.outputs.labels}}